no-inline-html: false
table-pipe-style: false
table-column-count: false
line-length: false
heading-start-left: false
ul-indent: false
list-marker-space: false
no-trailing-spaces: false
no-bare-urls: false
blanks-around-lists: false
blanks-around-headings: false
no-duplicate-heading: false
